[2017-05-31 01:42:56] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 01:42:56] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Connection Exception: Exception = HTTPSConnectionPool(host='10.243.14.80', port=443): Max retries exceeded with url: /sessions (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2123850>: Failed to establish a new connection: [Errno 111] Connection refused',))
[2017-05-31 01:42:56] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Failed
[2017-05-31 01:42:56] - [INFO] - [pylxca.pylxca_cmd.lxca_pyshell] - {'ip': '10.243.6.68', 'con': None}
[2017-05-31 01:42:56] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Connection Exception: Exception = Connection is not Initialized.
[2017-05-31 01:44:48] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 01:44:49] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 01:44:50] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 01:44:50] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-05-31 01:44:50] - [INFO] - [pylxca.pylxca_cmd.lxca_pyshell] - {'ip': '10.243.6.68', 'con': lxca_connection('https://10.240.199.19', USERID, debug=False)}
[2017-05-31 01:44:50] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 01:52:14] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 01:52:15] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 01:52:15] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 01:52:16] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-05-31 01:56:16] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 01:56:18] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 01:56:18] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 01:56:18] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-05-31 06:33:53] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 06:33:54] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 06:33:54] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 06:33:54] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-05-31 06:33:54] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-05-31 06:33:54] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 06:33:55] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
[2017-05-31 06:52:06] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 06:52:07] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 06:52:07] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 06:52:08] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-05-31 06:52:08] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-05-31 06:52:08] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 06:52:08] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
[2017-05-31 07:18:56] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 07:18:57] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:18:58] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:18:58] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-05-31 07:18:58] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-05-31 07:18:58] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:18:58] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
[2017-05-31 07:22:02] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 07:22:03] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:22:03] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:22:04] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-05-31 07:22:04] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-05-31 07:22:04] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:22:04] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
[2017-05-31 07:22:32] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-05-31 07:22:33] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:22:33] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:22:34] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-05-31 07:22:34] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-05-31 07:22:34] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-05-31 07:22:34] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
[2017-06-02 03:40:32] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-06-02 03:40:33] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:40:33] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:40:33] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-06-02 03:40:33] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-06-02 03:40:33] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:40:34] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
[2017-06-02 03:40:54] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-06-02 03:40:55] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:40:55] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:40:55] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-06-02 03:40:55] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-06-02 03:40:55] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:40:56] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
[2017-06-02 03:41:12] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-06-02 03:41:13] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:41:14] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:41:14] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-06-02 03:41:14] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-06-02 03:41:14] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:41:14] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
[2017-06-02 03:44:55] - [DEBUG] - [pylxca.pylxca_api.lxca_connection] - Establishing Connection
[2017-06-02 03:44:56] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:44:56] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:44:57] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection to LXCA Success
[2017-06-02 03:44:57] - [DEBUG] - [pylxca.pylxca_api.lxca_api] - Connection url:  1
[2017-06-02 03:44:57] - [WARNING] - [py.warnings] - /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[2017-06-02 03:44:57] - [ERROR] - [pylxca.pylxca_api.lxca_api] - Exception 404 Client Error: Not Found for url: https://10.240.199.19/manifests/1 Occurred while calling REST API for object manifests
